name: Reusable Pipeline

on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string
      dockerfile:
        required: true
        type: string
      environment:
        required: true
        type: string
    secrets:
      inherit: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t ${{ inputs.project }}:${{ github.sha }} -f ${{ inputs.dockerfile }} .
          docker push ${{ inputs.project }}:${{ github.sha }}

      - name: Deploy to environment
        run: |
          echo "Deploying to ${{ inputs.environment }} environment"
          # Adicione seus comandos de implantação aqui
