name: Reusable Pipeline

on:
  workflow_call:
    inputs:
      docker_username:
        required: true
        type: string
      docker_password:
        required: true
        type: string
      image_name:
        required: true
        type: string

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        run: |
          docker buildx create --use
          docker buildx inspect --bootstrap

      - name: Login to Docker Hub
        run: echo "${{ inputs.docker_password }}" | docker login -u "${{ inputs.docker_username }}" --password-stdin

      - name: Build Docker image locally
        run: |
          docker build -t ${{ inputs.image_name }}:latest -f Dockerfile .

      - name: Tag and push Docker image
        run: |
          docker tag ${{ inputs.image_name }}:latest ${{ inputs.image_name }}:${{ github.sha }}
          docker push ${{ inputs.image_name }}:${{ github.sha }}
